---
name: Auto create gitmoji labels
description: This action automatically creates gitmoji labels JIT

inputs:
    GITHUB_TOKEN:
        description: 'GitHub token'
        required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get all Gitmojis
      id: gitmojis
      shell: bash
      run: |
           curl -s https://gitmoji.dev/api/gitmojis | jq '.gitmojis[].emoji' > gitmojis.txt

    - name: Get gitmoji from PR title
      id: get-gitmoji
      shell: bash
      run: |
           gitmojis=$(cat gitmojis.txt)
           gitmoji=$(echo "${{ github.event.pull_request.title }}" | cut -d ' ' -f1)
           if [[ ! $gitmojis == *"$gitmoji"* ]]; then
             echo "Cannot create label as gitmoji not prefixed in PR title"
             exit 1
           else
             gitmoji_clean=$(echo $gitmoji | tr -d '[:space:]' | tr -d '[:punct:] | tr -d '\xEF\xB8\x8F')
             echo "gitmoji=$gitmoji_clean" >> $GITHUB_OUTPUT
           fi

    - name: Create label if not exists
      id: create-label
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
          echo ${{steps.get-gitmoji.outputs.gitmoji}}
          gh label list --json name | jq -er '.[] | select(.name | test("${{steps.get-gitmoji.outputs.gitmoji}}_gitmoji")) | .name' || gh label create ${{steps.get-gitmoji.outputs.gitmoji}}_gitmoji -c "$(openssl rand -hex 3)" -d "PRs with ${{steps.outputs.get-gitmoji.outputs.gitmoji}}_gitmoji" --force

    - name: remove labels ending in _gitmoji from PR
      id: remove-label
      shell: bash
      env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          gh pr view --json labels -q '.labels[] | select(.name | endswith("_gitmoji")) | .name' | tr -d '"' | while read -r label; do
            gh pr edit --remove-label $label
          done
    - name: Add label to PR
      id: add-label
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          gh pr edit --add-label ${{steps.get-gitmoji.outputs.gitmoji}}_gitmoji

branding:
    icon: 'check-circle'
    color: 'green'
