name: Create gitmoji label
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  create-gitmoji-label:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce gitmoji PR title
        uses: georgepstaylor/gitmoji-auto-label@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}