name: Create gitmoji label
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  create-gitmoji-label:
    runs-on: ubuntu-latest
    steps:
      - name: Create gitmoji label
        uses: georgepstaylor/gitmoji-auto-label@simplify-gitmoji-step-output
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}