name: Create release

on:
    workflow_dispatch:
        inputs:
            release_type:
                description: 'Type of release'
                required: true
                type: choice
                options:
                    - 'major'
                    - 'minor'
                    - 'patch'

jobs:
    release-job:
        runs-on: ubuntu-latest
        steps:
        - uses: georgepstaylor/gitmoji-release-action@425eed91df83ba575541fbe78c9a15b2ef1c8b2d
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            release_type: 'patch'
            auto_create_tag: true
            title_suffix: '- Release'         
