name: Create release

on:
    workflow_dispatch:
        inputs:
            release_type:
                description: 'Type of release'
                required: true
                type: choice
                options:
                    - 'major'
                    - 'minor'
                    - 'patch'

jobs:
    release-job:
        runs-on: ubuntu-latest
        steps:
        - uses: georgepstaylor/gitmoji-release-action@1d2d09b86c0353e299d95fcd0afd3d4750f80f3d
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            release_type: 'patch'
            auto_create_tag: true
            title_suffix: '- Release'         
