name: Create release

on:
    workflow_dispatch:
        inputs:
            release_type:
                description: 'Type of release'
                required: true
                type: choice
                options:
                    - 'major'
                    - 'minor'
                    - 'patch'

jobs:
    release-job:
        runs-on: ubuntu-latest
        steps:
        - uses: georgepstaylor/gitmoji-release-action@92bf3892ceb8525dc2de9d0a5d0d8a7268bee6f0
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            release_type: 'patch'
            auto_create_tag: true
            title_suffix: '- Release'         
